set -euo pipefail

runtime_dir() {
  if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
    printf '%s\n' "$XDG_RUNTIME_DIR"
  else
    printf '/run/user/%s\n' "$(id -u)"
  fi
}

env_file() {
  if [ -n "${DEVCONTAINER_GUI_ENV_FILE:-}" ]; then
    printf '%s\n' "$DEVCONTAINER_GUI_ENV_FILE"
  else
    printf '%s/devcontainer-gui-env.sh\n' "$(runtime_dir)"
  fi
}

usage() {
  cat <<'EOF'
devcontainer-gui-env refresh
devcontainer-gui-env status
devcontainer-gui-env print
EOF
}

wayland_discovery_dirs() {
  local uid
  local dirs
  local dir
  if [ -n "${DEVCONTAINER_GUI_WAYLAND_SCAN_DIRS:-}" ]; then
    dirs="${DEVCONTAINER_GUI_WAYLAND_SCAN_DIRS}:"
    while [ -n "$dirs" ]; do
      dir="${dirs%%:*}"
      dirs="${dirs#*:}"
      [ -n "$dir" ] && printf '%s\n' "$dir"
    done
    return 0
  fi

  uid="$(id -u)"
  printf '/run/user/%s\n' "$uid"
  printf '/tmp/user/%s\n' "$uid"
  printf '/tmp\n'
}

is_wayland_socket_candidate() {
  local path="$1"
  local name
  name="$(basename "$path")"
  case "$name" in
    *wayland*) ;;
    *) return 1 ;;
  esac
  [ -S "$path" ]
}

discover_wayland_socket() {
  local explicit_path
  local dir
  local path
  local best_path=""
  local best_mtime="-1"
  local mtime

  if [ -n "${WAYLAND_DISPLAY:-}" ]; then
    explicit_path="$(wayland_socket_path)" || return 1
    [ -S "$explicit_path" ] || return 1
    printf '%s\n' "$explicit_path"
    return 0
  fi

  while IFS= read -r dir; do
    [ -d "$dir" ] || continue
    for path in "$dir"/*; do
      [ -e "$path" ] || [ -L "$path" ] || continue
      is_wayland_socket_candidate "$path" || continue
      mtime="$(stat -Lc '%Y' "$path" 2>/dev/null || printf '0')"
      case "$mtime" in
        '' | *[!0-9]*)
          mtime=0
          ;;
      esac
      if [ -z "$best_path" ] || [ "$mtime" -gt "$best_mtime" ]; then
        best_path="$path"
        best_mtime="$mtime"
      fi
    done
  done < <(wayland_discovery_dirs)

  [ -n "$best_path" ] || return 1
  printf '%s\n' "$best_path"
}

wayland_display_for_socket() {
  local socket_path="$1"
  local runtime
  runtime="$(runtime_dir)"
  case "$socket_path" in
    "$runtime"/*)
      printf '%s\n' "${socket_path#"$runtime"/}"
      ;;
    *)
      printf '%s\n' "$socket_path"
      ;;
  esac
}

shell_quote() {
  local value="${1-}"
  local quoted="'"
  while [[ "$value" == *"'"* ]]; do
    quoted+="${value%%\'*}'\\''"
    value="${value#*\'}"
  done
  quoted+="$value'"
  printf '%s' "$quoted"
}

export_line() {
  local name="$1"
  local value="$2"
  printf 'export %s=' "$name"
  shell_quote "$value"
  printf '\n'
}

unset_lines() {
  printf 'unset XDG_SESSION_TYPE\n'
  printf 'unset GDK_BACKEND\n'
  printf 'unset QT_QPA_PLATFORM\n'
  printf 'unset SDL_VIDEODRIVER\n'
  printf 'unset CLUTTER_BACKEND\n'
  printf 'unset MOZ_ENABLE_WAYLAND\n'
  printf 'unset NIXOS_OZONE_WL\n'
}

gui_env_disabled() {
  case "${DEVCONTAINER_GUI_ENV:-1}" in
    0 | false | FALSE | no | NO | off | OFF)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

wayland_socket_path() {
  local display="${WAYLAND_DISPLAY:-}"
  [ -n "$display" ] || return 1
  case "$display" in
    /*)
      printf '%s\n' "$display"
      ;;
    *)
      printf '%s/%s\n' "$(runtime_dir)" "$display"
      ;;
  esac
}

has_wayland_socket() {
  discover_wayland_socket >/dev/null
}

has_x11_display() {
  [ -n "${DISPLAY:-}" ] || [ -n "${REMOTE_CONTAINERS_DISPLAY:-}" ]
}

detect_backend() {
  local forced="${DEVCONTAINER_GUI_BACKEND:-auto}"

  if gui_env_disabled; then
    printf 'disabled\n'
    return 0
  fi

  case "$forced" in
    "" | auto)
      if has_wayland_socket; then
        printf 'wayland\n'
      elif has_x11_display; then
        printf 'x11\n'
      else
        printf 'none\n'
      fi
      ;;
    wayland)
      if has_wayland_socket; then
        printf 'wayland\n'
      else
        printf 'none\n'
      fi
      ;;
    x11)
      if has_x11_display; then
        printf 'x11\n'
      else
        printf 'none\n'
      fi
      ;;
    *)
      printf 'invalid DEVCONTAINER_GUI_BACKEND: %s\n' "$forced" >&2
      return 2
      ;;
  esac
}

render_env() {
  local backend="$1"
  local socket_path=""
  local effective_wayland_display=""
  printf '# Generated by devcontainer-gui-env. Source this file from a shell.\n'
  printf '# backend=%s\n' "$backend"

  case "$backend" in
    wayland)
      if socket_path="$(discover_wayland_socket 2>/dev/null)"; then
        effective_wayland_display="$(wayland_display_for_socket "$socket_path")"
        export_line WAYLAND_DISPLAY "$effective_wayland_display"
      fi
      export_line XDG_SESSION_TYPE wayland
      export_line GDK_BACKEND wayland,x11
      export_line QT_QPA_PLATFORM 'wayland;xcb'
      export_line SDL_VIDEODRIVER wayland
      export_line CLUTTER_BACKEND wayland
      export_line MOZ_ENABLE_WAYLAND 1
      export_line NIXOS_OZONE_WL 1
      ;;
    x11)
      export_line XDG_SESSION_TYPE x11
      export_line GDK_BACKEND x11
      export_line QT_QPA_PLATFORM xcb
      export_line SDL_VIDEODRIVER x11
      export_line CLUTTER_BACKEND x11
      printf 'unset MOZ_ENABLE_WAYLAND\n'
      printf 'unset NIXOS_OZONE_WL\n'
      if [ -z "${DISPLAY:-}" ] && [ -n "${REMOTE_CONTAINERS_DISPLAY:-}" ]; then
        # shellcheck disable=SC2016
        printf 'if [ -z "${DISPLAY:-}" ]; then\n'
        printf '  export DISPLAY='
        shell_quote "$REMOTE_CONTAINERS_DISPLAY"
        printf '\n'
        printf 'fi\n'
      fi
      ;;
    none | disabled)
      unset_lines
      ;;
    *)
      printf 'unsupported backend: %s\n' "$backend" >&2
      return 2
      ;;
  esac
}

write_env_file() {
  local backend="$1"
  local target
  local target_dir
  local tmp
  target="$(env_file)"
  target_dir="$(dirname "$target")"
  mkdir -p "$target_dir"
  tmp="$(mktemp "$target_dir/.devcontainer-gui-env.XXXXXX")"
  if render_env "$backend" >"$tmp"; then
    chmod 0600 "$tmp"
    mv -f "$tmp" "$target"
  else
    rm -f "$tmp"
    return 1
  fi
}

print_status() {
  local backend="$1"
  local socket_path=""
  local effective_wayland_display=""
  local socket_valid=0
  if socket_path="$(discover_wayland_socket 2>/dev/null)"; then
    socket_valid=1
    effective_wayland_display="$(wayland_display_for_socket "$socket_path")"
  fi

  printf 'enabled='
  if gui_env_disabled; then
    printf '0\n'
  else
    printf '1\n'
  fi
  printf 'backend=%s\n' "$backend"
  printf 'env_file=%s\n' "$(env_file)"
  printf 'wayland_display=%s\n' "${WAYLAND_DISPLAY:-}"
  printf 'wayland_display_effective=%s\n' "$effective_wayland_display"
  printf 'wayland_socket=%s\n' "$socket_path"
  printf 'wayland_socket_valid=%s\n' "$socket_valid"
  printf 'display=%s\n' "${DISPLAY:-}"
  printf 'remote_containers_display=%s\n' "${REMOTE_CONTAINERS_DISPLAY:-}"
}

cmd="${1:-status}"
case "$cmd" in
  refresh)
    backend="$(detect_backend)"
    write_env_file "$backend"
    print_status "$backend"
    ;;
  status)
    backend="$(detect_backend)"
    print_status "$backend"
    ;;
  print)
    backend="$(detect_backend)"
    render_env "$backend"
    ;;
  -h | --help | help)
    usage
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
