name: build-image-rust-latest

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - flake.nix
      - flake.lock
      - images/**
      - lib/**
      - runtime/**
      - tests/**
      - .github/workflows/**

jobs:
  build:
    uses: ./.github/workflows/_build-image.yml
    with:
      image-target: rust-latest
