name: build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:

  # https://www.kenmuse.com/blog/dynamic-build-matrices-in-github-actions/
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.dataStep.outputs.myoutput }}
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30

      - name: dynamic matrix for next job
        id: dataStep
        run: |
          packages="$(nix eval --json $".#packages.x86_64-linux" --apply 'x: builtins.attrNames x' )"
          echo "myoutput=$(jq -cn --argjson packages "$packages" '{package: $packages}')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.packages) }}

    steps:
      - uses: actions/checkout@v4

      # https://discourse.nixos.org/t/building-docker-image-in-github-actions-leads-to-skopeo-related-issues/40636/4
      - name: Fix dockerTools.pullImage issue
        run: |
          sudo chmod 755 /run/containers
          sudo mkdir -p "/run/containers/$(id -u runner)"
          sudo chown runner: "/run/containers/$(id -u runner)"

      # # https://github.com/epics-extensions/EPNix/blob/e9cd66b48ac1342e1bf1ee3192e37b5087f78458/.github/workflows/build-checks.yml#L41-L50
      # - name: Enable KVM on Linux so NixOS tests can run
      #   run: |
      #     # Do this early in the process so nix installation detects the KVM feature.
      #     enable_kvm() {
      #       echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-install-nix-action-kvm.rules
      #       sudo udevadm control --reload-rules && sudo udevadm trigger --name-match=kvm
      #     }
      #     if [[ "$OSTYPE" =~ linux* ]]; then
      #       enable_kvm && echo 'Enabled KVM' || echo 'KVM is not available'
      #     fi

      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30

      - uses: nix-community/cache-nix-action@aee88ae5efbbeb38ac5d9862ecbebdb404a19e69 # v6
        with:
          primary-key: build-${{ runner.os }}-${{ matrix.package }}-${{ hashFiles('flake.lock') }}
          purge: true
          purge-last-accessed: 2629800 # 1 month
          purge-prefixes: build-${{ runner.os }}-${{ matrix.package }}-
          purge-primary-key: never

      - name: build ${{ matrix.package }}
        run: |
          nix run .#${{ matrix.package }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push ${{ matrix.package }}
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository_owner }}/devcontainers-${{ matrix.package }}"
          docker pull "$IMAGE_NAME:latest" || true
          ori_digest="$(docker inspect "$IMAGE_NAME:latest" | jq -r '.[] | .Id' || true)"
          echo ori_digest $ori_digest
          new_digest="$(docker inspect "${{ matrix.package }}:latest" | jq -r '.[] | .Id' || true)"
          echo new_digest $new_digest
          if [ "$new_digest" = "$ori_digest" ]; then
            echo no change
            exit 0
          fi
          docker tag "${{ matrix.package }}:latest" "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest"
